// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBdMjpAs_TRoNcbXZ4QcQiIgV8EhUBxEI',
    appId: '1:602883492301:android:88c04a7067e90cffed1c84',
    messagingSenderId: '602883492301',
    projectId: 'wmf-weight-tracker',
    databaseURL: 'https://wmf-weight-tracker-default-rtdb.firebaseio.com',
    storageBucket: 'wmf-weight-tracker.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS-QlCs72ATlJprtrN2remxKsS0RPPW2Q',
    appId: '1:602883492301:web:63317877bdbd64f2ed1c84',
    messagingSenderId: '602883492301',
    projectId: 'wmf-weight-tracker',
    authDomain: 'wmf-weight-tracker.firebaseapp.com',
    databaseURL: 'https://wmf-weight-tracker-default-rtdb.firebaseio.com',
    storageBucket: 'wmf-weight-tracker.firebasestorage.app',
    measurementId: 'G-LG3QYGH6SH',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS-QlCs72ATlJprtrN2remxKsS0RPPW2Q',
    appId: '1:602883492301:web:63317877bdbd64f2ed1c84',
    messagingSenderId: '602883492301',
    projectId: 'wmf-weight-tracker',
    authDomain: 'wmf-weight-tracker.firebaseapp.com',
    databaseURL: 'https://wmf-weight-tracker-default-rtdb.firebaseio.com',
    storageBucket: 'wmf-weight-tracker.firebasestorage.app',
    measurementId: 'G-LG3QYGH6SH',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAQC2LnmcN-WTKj1mm7IBqi-xTl384ZGY',
    appId: '1:602883492301:ios:a6e325afd31e3d49ed1c84',
    messagingSenderId: '602883492301',
    projectId: 'wmf-weight-tracker',
    databaseURL: 'https://wmf-weight-tracker-default-rtdb.firebaseio.com',
    storageBucket: 'wmf-weight-tracker.firebasestorage.app',
    iosBundleId: 'com.example.weightTracker',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAQC2LnmcN-WTKj1mm7IBqi-xTl384ZGY',
    appId: '1:602883492301:ios:a6e325afd31e3d49ed1c84',
    messagingSenderId: '602883492301',
    projectId: 'wmf-weight-tracker',
    databaseURL: 'https://wmf-weight-tracker-default-rtdb.firebaseio.com',
    storageBucket: 'wmf-weight-tracker.firebasestorage.app',
    iosBundleId: 'com.example.weightTracker',
  );

}